version: '3.8'
services:
  web:
    image: nginx
    volumes:
    - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    - ./public:/example.com/
    ports:
    - "8080:80"
  php:
    build: .
    volumes:
    - ./public:/example.com/
